overrides:
  "@chat-adapter/telegram": 4.36.0
  "@vite-hub/agent": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/agent@63a3ecc"
  chat: 4.36.0
patchedDependencies:
  "@chat-adapter/telegram@4.36.0": patches/@chat-adapter__telegram@4.36.0.patch
  chat@4.36.0: patches/chat@4.36.0.patch
